# Generated by Django 3.2.22 on 2023-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_posts', '0002_auto_20231025_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.12345, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.12345, max_digits=9),
            preserve_default=False,
        ),
    ]
